// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZp144OmHEkevASMrDvyvEBbZ260eimNE',
    appId: '1:83194182055:web:02f6f5e9b3019a13061e82',
    messagingSenderId: '83194182055',
    projectId: 'newproject-b8377',
    authDomain: 'newproject-b8377.firebaseapp.com',
    storageBucket: 'newproject-b8377.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP7ukSZz7PvnXTg9fqhygUx7PgiXR_kgE',
    appId: '1:83194182055:android:2dd8ea91e58c7dbf061e82',
    messagingSenderId: '83194182055',
    projectId: 'newproject-b8377',
    storageBucket: 'newproject-b8377.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZp144OmHEkevASMrDvyvEBbZ260eimNE',
    appId: '1:83194182055:web:1444b49abbe2f35a061e82',
    messagingSenderId: '83194182055',
    projectId: 'newproject-b8377',
    authDomain: 'newproject-b8377.firebaseapp.com',
    storageBucket: 'newproject-b8377.appspot.com',
  );
}
